development:
  adapter: mysql
  database: rlingcms
  username: root
  password: root


test: &test
  adapter: mysql
  database: rlingcms_test
  username: root
  password: root


production:
  adapter: mysql
  database: rlingcms
  username: root
  password: root

cucumber:
  <<: *test
