development:
  adapter: mysql
  database: rling1
  username: root
  password: root


test: &test
  adapter: mysql
  database: rling1_test
  username: root
  password: root


production:
  adapter: mysql
  database: rling1
  username: root
  password: root

cucumber:
  <<: *test
