development:
  adapter: mysql
  database: rlingsite
  username: root
  password: root


test: &test
  adapter: mysql
  database: rling_test
  username: root
  password: root


production:
  adapter: mysql
  database: rling
  username: root
  password: root

cucumber:
  <<: *test
