development:
  adapter: mysql
  database: rling3
  username: root
  password: root


test: &test
  adapter: mysql
  database: rling3_test
  username: root
  password: root


production:
  adapter: mysql
  database: rling3
  username: root
  password: root

cucumber:
  <<: *test
